### ISSUE TITLE
Delete TF model in GPU memory (predictions.runner)

### ISSUE THREAD

**Issue by SeungHeonDoh** [neuralaudio/hear-eval-kit#308]
I'm using the TF model (tensorflow==2.5.0) as an embedding extractor.
When loading a TF model, it occupies the entire GPU memory.

In the case of downstream prediction, to check the embedding size of the model, **predictions.runner** load the model with the following code.

```
  module_clr = import_module(module)
  # Load the model using the model weights path if they were provided
  if model is not None:
      print(f"Loading {module} using: {model}, {model_options_dict}")
      model_obj = module_clr.load_model(model, **model_options_dict)  # type: ignore
  else:
      print(f"Loading {module} using: {model}, {model_options_dict}")
      model_obj = module_clr.load_model("", **model_options_dict)  # type: ignore
  
  scene_embedding_size = model_obj.scene_embedding_size
  timestamp_embedding_size = model_obj.timestamp_embedding_size
  
  # Free model obj
  model_obj = None
```

Despite **model_obj = None**  , the TF model remains in GPU memory, which causes an out of memory error in downstream evaluation.

Can you help me clean the **TF model** from GPU memory?

**Comment by turian** [comment]
@SeungHeonDoh which version of hear-eval-kit do you have? can you try upgrading the pypi version?

The latest version of hear-eval-kit should fix this:

```
        embedding_size = json.load(open(train_embedding_dimensions))[1]
```

It computes the embedding size using the JSON file

**Comment by SeungHeonDoh** [comment]
I have built the environment via the docker file below.
- https://github.com/neuralaudio/hear-eval-kit/blob/main/docker/Dockerfile-cuda11.2

However, the heareval version was installed as 2021.0.3 version, and the problem was solved by installing 2021.0.5 version.

```
pip install heareval==2021.0.5
```

thank you!

**Comment by turian** [comment]
@SeungHeonDoh I believe that the docker image in docker hub also has the latest heareval.
